export const GOODS_RECEIPT_STRINGS = {
  title: 'Warehouse Intake & Quality Checks',
  subtitle: 'Receive incoming produce against purchase orders, perform the 5-point quality inspection, or issue quality counter-offers.',
  receiveButton: '+ Receive Goods (GRN)',
  tabs: {
    all: 'All Receipts',
    awaitingQc: 'Awaiting QC',
    accepted: 'Accepted',
    partiallyAccepted: 'Partially Accepted',
    rejected: 'Rejected',
    counterOffered: 'Counter-Offered',
  },
  table: {
    grnNumber: 'GRN Number',
    poNumber: 'PO Number',
    crop: 'Crop & Grade',
    grossQty: 'Gross Qty (kg)',
    acceptedQty: 'Accepted (kg)',
    rejectedQty: 'Rejected (kg)',
    vehicleNumber: 'Vehicle No',
    status: 'Status',
    receivedAt: 'Received At',
    actions: 'Actions',
    emptyMessage: 'No goods receipts found in queue.',
  },
  modal: {
    receiveTitle: 'New Goods Intake (GRN)',
    poId: 'Purchase Order ID (UUID)',
    warehouseId: 'Warehouse ID (UUID)',
    grossQty: 'Gross Quantity (kg)',
    vehicleNumber: 'Vehicle Number (e.g. TN43AB1234)',
    photos: 'Photo URLs (comma-separated)',
    remarks: 'Intake Remarks',
    submitReceive: 'Create Goods Receipt',
    cancel: 'Cancel',

    qcTitle: '5-Point Quality Inspection',
    assignedGrade: 'Assigned Grade',
    outcome: 'Inspection Outcome',
    acceptedQty: 'Accepted Quantity (kg)',
    rejectedQty: 'Rejected Quantity (kg)',
    rejectionReason: 'Rejection Reason / Defect Notes',
    priceAdjustment: 'Price Adjustment (₹/kg)',
    submitQc: 'Complete Quality Check',

    counterTitle: 'Quality Shortfall Counter-Offer',
    counterPrice: 'Revised Price (₹/kg)',
    counterQty: 'Countered Quantity (kg)',
    counterMessage: 'Reason / Message to Farmer',
    submitCounter: 'Send Counter-Offer (24h Expiry)',
  },
  qcPoints: {
    appearance: '1. Appearance & Color',
    sizeUniformity: '2. Size & Shape Uniformity',
    moisture: '3. Moisture Content',
    damagePest: '4. Pest Damage & Blemishes',
    freshness: '5. Firmness & Freshness',
  },
} as const;
